apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: acmefit
    service: catalog
spec:
  ports:
    - name: http-catalog
      protocol: TCP
      port: 8082
  selector:
    app: acmefit
    service: catalog