apiVersion: v1
kind: Service
metadata:
  name: catalog-mongo-lb
  labels:
    app: acmefit
    service: catalog-db
spec:
  ports:
    - port: 27017
      name: mongo-catalog
      protocol: TCP
  type: LoadBalancer
  selector:
    app: acmefit
    service: catalog-db