apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: acmefit
    service: order
spec:
  ports:
    - name: http-order
      protocol: TCP
      port: 6000
  selector:
    app: acmefit
    service: order