apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app: acmefit
    service: cart
spec:
  ports:
    - name: http-cart
      protocol: TCP
      port: 5000
  selector:
    app: acmefit
    service: cart