apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"redis-server","namespace":"yelb"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"redis-server"}},"template":{"metadata":{"labels":{"app":"redis-server","tier":"cache"}},"spec":{"containers":[{"image":"redis:4.0.2","name":"redis-server","ports":[{"containerPort":6379}]}]}}}}
  creationTimestamp: "2021-08-01T14:45:55Z"
  generation: 1
  name: redis-server
  namespace: yelb
  uid: 1ebdfd93-59fa-4283-a53a-a68f501a45bf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-server
        tier: cache
    spec:
      containers:
      - image: redis:4.0.2
        imagePullPolicy: IfNotPresent
        name: redis-server
        ports:
        - containerPort: 6379
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-01T14:46:35Z"
    lastUpdateTime: "2021-08-01T14:46:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-01T14:45:56Z"
    lastUpdateTime: "2021-08-01T14:46:35Z"
    message: ReplicaSet "redis-server-74556bbcb7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1