apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"yelb-ui","namespace":"yelb"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"yelb-ui"}},"template":{"metadata":{"labels":{"app":"yelb-ui","tier":"frontend"}},"spec":{"containers":[{"image":"mreferre/yelb-ui:0.6","name":"yelb-ui","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2021-08-01T14:45:55Z"
  generation: 1
  name: yelb-ui
  namespace: yelb
  uid: dbe25a61-b3b3-4c61-baf1-0be3a3159537
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: yelb-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yelb-ui
        tier: frontend
    spec:
      containers:
      - image: mreferre/yelb-ui:0.6
        imagePullPolicy: IfNotPresent
        name: yelb-ui
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-01T14:46:58Z"
    lastUpdateTime: "2021-08-01T14:46:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-01T14:45:55Z"
    lastUpdateTime: "2021-08-01T14:46:58Z"
    message: ReplicaSet "yelb-ui-8f54fd88c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1