apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"yelb-appserver","namespace":"yelb"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"yelb-appserver"}},"template":{"metadata":{"labels":{"app":"yelb-appserver","tier":"middletier"}},"spec":{"containers":[{"image":"mreferre/yelb-appserver:0.5","name":"yelb-appserver","ports":[{"containerPort":4567}]}]}}}}
  creationTimestamp: "2021-08-01T14:45:56Z"
  generation: 1
  name: yelb-appserver
  namespace: yelb
  uid: 94a4c166-c568-4ba7-961e-c1d79699aec6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: yelb-appserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yelb-appserver
        tier: middletier
    spec:
      containers:
      - image: mreferre/yelb-appserver:0.5
        imagePullPolicy: IfNotPresent
        name: yelb-appserver
        ports:
        - containerPort: 4567
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-01T14:47:43Z"
    lastUpdateTime: "2021-08-01T14:47:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-01T14:45:56Z"
    lastUpdateTime: "2021-08-01T14:47:43Z"
    message: ReplicaSet "yelb-appserver-d584bb889" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1